apiVersion: v2
name: piwigo
description: Third-party Helm chart for Piwigo photo gallery application with persistence and extensibility
type: application
version: 1.0.0
appVersion: "latest"
maintainers:
  - name: Kianoosh Kashefi
    email: kianoosh.kashefi@pm.me
keywords:
  - piwigo
  - photo
  - gallery